import type { Metadata } from 'next'
import Footer from './components/main/Footer'
import Header from './components/main/Header'
import Logo from './components/main/Logo'
import Navbar from './components/main/Navbar'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Edem flowers Lviv',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className='text-white font-thin'>
				<Header />
				<div className='w-[75%] m-auto'>
					<Logo />
					<Navbar />
				</div>
				<div className='w-[90%] sm:w-[75%] m-auto'>{children}</div>
				<Footer />
			</body>
		</html>
	)
}
